### ISSUE TITLE
Globals, enums, etc?

### ISSUE THREAD

**Issue by KaidenValor** [hudwave/lets-make-lasagne#1]
Thank you for this amazing documentation, I've been following your guidelines to recreate my player object and I'm already seeing the benefits.

I have an amateur question if you willing to answer. What's your advice on the best way to define global variables, enums, etc? Previously I'd read that creating a manager object, doing it all in that and then having that be the first object created is the best way... But in the interest of removing dependency on any specific objects would I be better defining these in a script file called globals (or something similar) since those are loaded independently and before any objects? 

Thanks in advance if you do happen to answer.

**Comment by hudwave** [comment]
Thanks, I'm glad you're finding it useful! You make a good point about globals, I should add a section about them.

In terms of where to define globals, I usually have a non-persistent object that acts as the entry point to the game called `oInit`. I put this in the first room that is loaded called `rInit`. `oInit` will then setup all the global variables that are required for the game and handle loading the first actual room. Generally you won't be creating new global variables once the game has begun so it does make sense to do that first. You have to create dependencies somehwere so this is a good place for globals.

Essentially, any object you declare as global is explicitly a dependency when used by another object. So think carefully about what you choose to make global. That's not to say you shouldn't use globals at all. Game development is very different to traditional software development, often lines are blurred UI, data and controllers. Systems such as audio or input can also be used almost anywhere in your game, from player, enemies to the HUD. Trying to insert this as a dependency where it's needed could be a lot more work (and make the code more verbose) than just accessing it globally. And the goal is to make a working game right, not perfect code.

I think the key point to takeaway from these tutorials is not to eliminate all dependencies or that dependencies are always bad. But rather that directly accessing a dependency strongly couples your object to the dependency. This is not always a problem, but when it does become a problem you need to look for ways to decouple the dependency. With experience and trial and error you will be able to identify where this might happen and if you actually need to decouple them.

Enums and macros are slightly different as these are constants so it doesn't really matter where you put them. I would tend to put these in the files closest to the code where they are most relevant, so that anyone reading the code (including yourself at a later date) can see quickly what they relate to. Some constants might not fit into a specific place, tile size for instance. I would put these all in a separate script called constants or something similar.

Finally in the latest beta (2023.100) there is a new mechanism for accessing static variables and methods on structs and constructor functions. This might eliminate the need for a lot of global variables so keep an eye out for that.

**Comment by KaidenValor** [comment]
Thanks for your reply. That all makes sense and is what I have been doing already for globals, enums and macros so I'll just stick to doing that. 

Your guide has definitely provided me with a framework for structuring my code in a much more organised way, so again thank you for writing everything up.
